### ISSUE TITLE
Feature: New Power System?

### ISSUE THREAD

**Issue by DylanInvents** [LopyLuna/Create-Calamity#19]
basically electric rotational power, called ESU, used to power all calamity machines and requires a transformer block to convert SU to ESU and a little bit of power from something like a furnace engine or smthing

**Comment by nullTheCoder** [comment]
Why?

**Comment by DylanInvents** [comment]
> Why?

because then the player has a little more trouble using the machines, making them just that little harder to get and that little dopamine spike when you get it all working
also just making a new power system building off of it instead of basing it all on the old one is kind of innovative

**Comment by PriestOfFern** [comment]
> innovative

Ah yes retextured create SU, the height of innovation

**Comment by DylanInvents** [comment]
> > innovative
> 
> Ah yes retextured create SU, the height of innovation

oh shush atleast i tried to defend my argument
